# Generated by Django 2.1.5 on 2019-01-16 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_section_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='visible',
            field=models.BooleanField(),
        ),
    ]
