# Generated by Django 2.1.5 on 2019-01-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20190116_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='open',
        ),
    ]
