# Generated by Django 2.1.5 on 2019-01-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_imagequote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagequote',
            name='image',
        ),
        migrations.AddField(
            model_name='imagequote',
            name='image_filename',
            field=models.CharField(default='temp', max_length=50),
            preserve_default=False,
        ),
    ]
