# Generated by Django 2.1.5 on 2019-01-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0010_item_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
